import {
  createIcons,
  Crown,
  Shirt,
  Compass,
  Sparkles,
  WandSparkles,
  BookOpen,
  Gift,
  Coins,
  Gem,
  ChevronRight,
  ChevronLeft,
  Check,
  Lock,
  Camera,
  RotateCcw,
  Volume2,
  VolumeX,
  Settings,
  X,
  Flower2,
  Heart,
  Waves,
  Snowflake,
  Castle,
  Scissors,
  Footprints,
  Feather,
  Star,
  Plus,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Download,
  Upload,
  Bookmark,
  Play,
  MapPin,
  Diamond,
  Palette,
  RefreshCw,
  Info,
  CheckCheck,
} from "lucide";
import type { Item } from "./simulation/data";
import { wardrobeArt } from "./wardrobe-art";
export const icon = (name: string, cls = "") =>
  `<i data-lucide="${name}" class="${cls}" aria-hidden="true"></i>`;
export function icons() {
  createIcons({
    icons: {
      Crown,
      Shirt,
      Compass,
      Sparkles,
      WandSparkles,
      BookOpen,
      Gift,
      Coins,
      Gem,
      ChevronRight,
      ChevronLeft,
      Check,
      Lock,
      Camera,
      RotateCcw,
      Volume2,
      VolumeX,
      Settings,
      X,
      Flower2,
      Heart,
      Waves,
      Snowflake,
      Castle,
      Scissors,
      Footprints,
      Feather,
      Star,
      Plus,
      ArrowUp,
      ArrowDown,
      ArrowLeft,
      ArrowRight,
      Download,
      Upload,
      Bookmark,
      Play,
      MapPin,
      Diamond,
      Palette,
      RefreshCw,
      Info,
      CheckCheck,
    },
    attrs: { "stroke-width": 1.6 },
  });
}
export function itemArt(item: Item) {
  return wardrobeArt(item);
}
